services:
  fast_zero_2025_database:
    image: postgres
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  fast_zero_2025_app:
    image: fast_zero_2025
    build: .
    entrypoint: ./entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - fast_zero_2025_database
    environment:
      DATABASE_URL: postgresql+psycopg://app_user:app_password@fast_zero_2025_database:5432/app_db

volumes:
  pgdata: