"""alter username column to unique

Revision ID: 75b86115f30d
Revises: 626b83bf6dae
Create Date: 2025-06-20 18:04:56.136465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75b86115f30d'
down_revision: Union[str, Sequence[str], None] = '626b83bf6dae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.create_unique_constraint('uq_users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op: 
        batch_op.drop_constraint('uq_users', type_='unique')
    # ### end Alembic commands ###
